SELECT T.ENTRADAID,T.ORDEM,R.DESCRICAO, P.NOMEFANTASIA, T.CATEGORIA, T.QUANTIDADE, T.DATAENTRADA,T.PRECO,T.DESCONTO,T.TOTAL,T.COMPRADOR, T.PARCELAS FROM ENTRADAS AS T INNER JOIN FORNECEDORES AS P ON T.FORNECEDORID = P.ID INNER JOIN PRODUTOS AS R ON T.PRODUTOID = R.ID WHERE T.ENTRADAID = 34;

